In [1]:
import numpy as np
import scipy.stats as ss

In [2]:
# choose sample size
T=750
# Generate sample for x,y
mu=(0,0,0)
cov=[[1,0,0.8],\
   [0,1,0],\
   [0.8,0,1]]
cov

[[1, 0, 0.8], [0, 1, 0], [0.8, 0, 1]]

In [3]:
# F= Time variying regression variable
F= np.random.multivariate_normal(mu, cov, T)

X=np.column_stack([np.ones((T,1)),F])

N=X.shape
N

(750, 4)

In [4]:
# Define co-efficient Matrix, Defrine rank to be N[1] * 1
beta =np.array([0.56,2.53,2.05, 1.78])
#               ,[1.5,2.00,1.05,1.38])
print(beta)
# beta.shape() = (N[1],1)

[0.56 2.53 2.05 1.78]


In [5]:
# Generate sample of Y
Y= X@beta+np.random.normal(0,1,(T,1))
print(Y)

[[12.37476022  5.02463117 -2.00378506 ...  4.37074044  5.46549222
   2.57280908]
 [10.255235    2.90510594 -4.12331028 ...  2.25121522  3.345967
   0.45328386]
 [ 9.95584872  2.60571966 -4.42269656 ...  1.95182894  3.04658072
   0.15389758]
 ...
 [10.6883701   3.33824105 -3.69017518 ...  2.68435033  3.7791021
   0.88641896]
 [10.39821729  3.04808824 -3.98032799 ...  2.39419751  3.48894929
   0.59626615]
 [11.62715314  4.27702408 -2.75139214 ...  3.62313336  4.71788514
   1.82520199]]


#### OLS Regression Starts
- linear regression of Y: Tx1 on 
- regeressor X:TxN

In [6]:
# inear regression of Y: Tx1 on
# regeressor X:TxN
invXX = np.linalg.inv(X.transpose()@X)
print('invXX:         ', invXX)

#  Coefficients:
beta_hat = invXX@X.transpose()@Y
print('beta_hat:         ',beta_hat)

# Predictive values of using OLS
y_hat = X@beta_hat
print('y_hat:         ',y_hat)

# residual from OLS
residuals= Y-y_hat
print('residuals:         ',residuals)

# Variance of residuLA
sigma2 = (1/T)*residuals.transpose()@residuals
print('sigma2:         ',sigma2)
sigma = np.sqrt(sigma2) 
print('sigma:         ',sigma)



invXX:          [[ 1.33388533e-03  9.08729083e-07  2.48775623e-05  9.23864106e-06]
 [ 9.08729083e-07  4.26916635e-03 -3.63529190e-05 -3.40442136e-03]
 [ 2.48775623e-05 -3.63529190e-05  1.27626853e-03  6.36268638e-05]
 [ 9.23864106e-06 -3.40442136e-03  6.36268638e-05  4.01370468e-03]]
beta_hat:          [[10.87701308  3.52688402 -3.50153221 ...  2.8729933   3.96774507
   1.07506193]
 [ 0.12965323  0.12965323  0.12965323 ...  0.12965323  0.12965323
   0.12965323]
 [ 0.01321042  0.01321042  0.01321042 ...  0.01321042  0.01321042
   0.01321042]
 [-0.02491121 -0.02491121 -0.02491121 ... -0.02491121 -0.02491121
  -0.02491121]]
y_hat:          [[11.12131861  3.77118956 -3.25722667 ...  3.11729884  4.21205061
   1.31936747]
 [10.85620452  3.50607547 -3.52234076 ...  2.85218475  3.94693652
   1.05425338]
 [10.81242598  3.46229693 -3.5661193  ...  2.80840621  3.90315798
   1.01047484]
 ...
 [10.96981416  3.6196851  -3.40873112 ...  2.96579438  4.06054616
   1.16786302]
 [10.97629929  3.62617024 

In [7]:
# If Ridge/lasso/elastic net
# obj_func = sigma2 + 0.5* abs(beta_hat) +  0.5* (beta_hat**2)

# return obj_func
# To solve for beta

In [10]:
# Varience-covarience matrix of beta hat
varcov_beta_hat= (sigma2)*invXX

std_beta_hat= np.sqrt(T* np.diag(varcov_beta_hat))

ValueError: operands could not be broadcast together with shapes (750,750) (4,4) 

In [ ]:
R_square = 1- (residuals.transpose()@residuals)/(T*np.sqrt)

adj_R_square =1- (1-R_square) * (T-1)(T-N[1])

In [ ]:
#  test each coefficient beta: beta_i
# My Null Hypothiis : beta_i=0
t_stats= (beta_hat.transpose()-0)std_beta_hat

p_val = 1-ss.norm.cdf(t_stat)


# F test : Test of joint significance of model
F_stat = (beta_hat.transpose)@np.lineage.inv(varcov_beta)@beta_hat
(residuals.transpose()@residuals/(T-N[1]))

p_val_F= 